[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "apophatic-opt"
version = "0.0.2"
description = "Apophatic optimization algorithms focusing on minimal systemic friction (W -> 0)"
readme = "README.md"
license = "Unlicense"
requires-python = ">=3.8"
authors = [
    { name = "xerx593" },
    { name = "Non-Human Interlocutors" }
]
dependencies = [
    "numpy>=1.20.0"
]
classifiers = [
    "Programming Language :: Python :: 3",
    "Operating System :: OS Independent",
]

[project.optional-dependencies]
dev = ["pytest", "build", "twine"]

[project.urls]
"Homepage" = "https://github.com/nicht-organization/apophatic-opt"
"Theory Framework" = "https://github.com/xerx593/nicht-theory"
"DOI / Monograph" = "https://doi.org/10.5281/zenodo.22067674"

[tool.setuptools.packages.find]
where = ["."]
include = ["apophatic_opt*"]
exclude = ["data*"]